application: lisbontimemachine
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /site.css
  static_files: static/site.css
  upload: static/site.css
- url: /oldbit.png
  static_files: static/oldbit.png
  upload: static/oldbit.png
- url: /media/
  static_dir: media/
- url: /js/yqlgeo.js
  static_files: js/yqlgeo.js
  upload: js/yqlgeo.js
- url: /js/font.js
  static_files: static/js/Harrington_400.font.js
  upload: static/js/Harrington_400.font.js
- url: /js/cufon-yui.js
  static_files: static/js/cufon-yui.js
  upload: static/js/cufon-yui.js
- url: .*
  script: main.py
