application: lisbontimemachine
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /site.css
  static_files: static/site.css
  upload: static/site.css
- url: /js/yqlgeo.js
  static_files: js/yqlgeo.js
  upload: js/yqlgeo.js
- url: .*
  script: main.py
